/* 
  Sketch generated by the Arduino IoT Cloud Thing "homeAutomation"
  https://create.arduino.cc/cloud/things/a51b5cee-aa39-4a6a-9ff4-bd11a615d5e9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch switch_1;
  CloudSwitch switch_2;
  CloudSwitch switch_3;
  CloudSwitch switch_4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

void onSwitch1Change() {
  // Do something
}


void onSwitch2Change() {
  // Do something
}


void onSwitch3Change() {
  // Do something
}


void onSwitch4Change() {
  // Do something
}
